In [84]:
### Steps
# Preprocess data in R 
# Load in data
# Create training and testing data
# Run model (figure out cv search and how to alter this)
# Run model with random cv search
# Figure out how to evaluate the model (get multiple measures at once)
# Save the model
# Export the predicted values
# Load in the model and run again with new data from FHHC

import pandas as pd
import numpy as np
import xgboost as xgb
from xgboost import XGBClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV

In [85]:
house_dat = pd.read_csv("house_dat_8_13_20.csv", delimiter = ",")

In [39]:
house_dat.head()

Quarter  Gender  RaceWhite  RaceBlack  Agegroup  OverallHealth  \
0        2       1          0          1       8.0            4.0   
1        1       0          1          0       6.0            1.0   
2        1       0          1          0       8.0            2.0   
3        1       1          1          0       7.0            4.0   
4        2       0          0          1       7.0            2.0   

   CapableManagingHealthCareNeeds  HandlingDailyLife  ControlLife  \
0                             3.0                2.0          3.0   
1                             1.0                4.0          4.0   
2                             1.0                2.0          4.0   
3                             2.0                2.0          2.0   
4                             1.0                5.0          5.0   

   DealWithCrisis  ...  EverServed  ActiveDuty_Else  NightsHomeless  aiety  \
0             2.0  ...           0                1             0.0      0   
1             4.0  ...           0                0            12.0      0   
2             4.0  ...           0                0            26.0      0   
3             4.0  ...           0                1            30.0      0   
4             5.0  ...           0                1             0.0      0   

   mdd_r  mdd_s  another_s_ident  drug_use  er_hos_use_base  jail_arrest_base  
0      0      0                0       9.0              0.0               0.0  
1      0      0                1      12.0              0.0               0.0  
2      0      0                0       9.0              4.0               2.0  
3      1      0                0       9.0              0.0               0.0  
4      0      0                0      12.0              0.0               0.0  

[5 rows x 54 columns]

In [86]:
house_dat.shape

(2101, 54)

In [87]:
### Break into testing and training
from sklearn.model_selection import train_test_split
y = house_dat[["Housing.y"]]
predictors = house_dat.drop(["Housing.y"], axis = 1)
### Need to make this a horitzontal array not sure why
y = y.values.ravel()
predictors = predictors.to_numpy()
X_train, X_test, y_train, y_test = train_test_split(predictors, y, test_size = .20, random_state = 53)

In [88]:
y_train

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [116]:
### Figure out how to get set up a Random search for xgboost (should be the same as previous random search)
from sklearn.model_selection import RandomizedSearchCV
xclas = XGBClassifier()  # and for classifier  
xclas.fit(X_train, y_train)  
pred_xclas =  xclas.predict(X_test)
pred_xclas

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,

In [114]:
from sklearn.model_selection import cross_validate
from sklearn.metrics import confusion_matrix
scoring = ['accuracy', 'precision', 'balanced_accuracy']
cv_results = cross_validate(xclas.fit(X_train, y_train) , X_train, y_train, cv=5, scoring=scoring)
cv_results

{'fit_time': array([0.15203905, 0.14604545, 0.14196086, 0.15003562, 0.1440444 ]),
 'score_time': array([0.0030129 , 0.00198865, 0.00399923, 0.00200105, 0.00299549]),
 'test_accuracy': array([0.86011905, 0.86607143, 0.85416667, 0.86011905, 0.83333333]),
 'test_precision': array([0.8650519 , 0.88970588, 0.86363636, 0.88321168, 0.86545455]),
 'test_balanced_accuracy': array([0.73449612, 0.7809437 , 0.7337093 , 0.76828548, 0.7288578 ])}

In [145]:
### Get a confusion matrix and then get sensitivity by hand
con_mat = confusion_matrix(y_test, pred_xclas)
#sensitivity <- TP / (TP + FN)
#specificity <- TN / (TN + FP)
con_mat
#tn, fp, fn, tp
sensitivity =  con_mat[1][1] / (con_mat[1][1] + con_mat[1][0])
specificity = con_mat[0][0] / (con_mat[0][0] + con_mat[0][1])
### 
balanced_accuracy =  (sensitivity+specificity)/2


In [231]:
### Fix this later
sensitivity = pd.DataFrame(sensitivity, columns = ["sensitivity"], index = [0])
specificity = pd.DataFrame(specificity, columns = ["specificity"], index = [0])
balanced_accuracy = pd.DataFrame(balanced_accuracy, columns = ["balanced_accuracy"], index = [0])

frames = [sensitivity, specificity, balanced_accuracy]
metrics_dat = pd.concat(frames, axis = 1)
metrics_dat

sensitivity  specificity  balanced_accuracy
0     0.931373     0.591304           0.761338

In [174]:
# Figure out good values for these
## sum(negative instances) / sum(positive instances)
## Good for unbalanced weights
#Description of the parameters: https://xgboost.readthedocs.io/en/latest/parameter.html
y_panda = pd.DataFrame(y)
y_panda.describe()

0
count  2101.000000
mean      0.757734
std       0.428556
min       0.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       1.000000

In [190]:
# Develop develop one for random grid search
params = {  
    "max_depth": [6,12,15, 18],
    "eta": [.01, .001, .3],
    "colsample_bytree": [.5, .6, .7],
    "subsample": [.5, .6, .7],
    'lambda': [1, 1.1, 1.2, 1.3, 1.4],
    'alpha': [0, .1, .2, .3],
    "scale_pos_weight ": [.25, .5, 1],
}

In [191]:
xclas_random = XGBClassifier()
gs = RandomizedSearchCV(xclas_random, params, n_jobs=-1, cv = 10)  
gs.fit(X_train, y_train)  

RandomizedSearchCV(cv=10, estimator=XGBClassifier(), n_jobs=-1,
                   param_distributions={'alpha': [0, 0.1, 0.2, 0.3],
                                        'colsample_bytree': [0.5, 0.6, 0.7],
                                        'eta': [0.01, 0.001, 0.3],
                                        'lambda': [1, 1.1, 1.2, 1.3, 1.4],
                                        'max_depth': [6, 12, 15, 18],
                                        'scale_pos_weight ': [0.25, 0.5, 1],
                                        'subsample': [0.5, 0.6, 0.7]})

In [213]:
#best_estimator_
#best_score_ 
#best_params_
gs.best_estimator_
gs.best_score_

0.8720238095238095

In [207]:
pred_best_random =  gs.predict(X_test)
pred_best_random

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,

In [208]:
### Get a confusion matrix and then get sensitivity by hand
con_mat = confusion_matrix(y_test, pred_best_random)
#sensitivity <- TP / (TP + FN)
#specificity <- TN / (TN + FP)
con_mat
#tn, fp, fn, tp
sensitivity =  con_mat[1][1] / (con_mat[1][1] + con_mat[1][0])
specificity = con_mat[0][0] / (con_mat[0][0] + con_mat[0][1])
### 
balanced_accuracy =  (sensitivity+specificity)/2

In [230]:
### Fix this later
##
gs.best_score_
sensitivity = pd.DataFrame(sensitivity, columns = ["sensitivity"], index = [0])
specificity = pd.DataFrame(specificity, columns = ["specificity"], index = [0])
balanced_accuracy = pd.DataFrame(balanced_accuracy, columns = ["balanced_accuracy"], index = [0])
frames = [sensitivity, specificity, balanced_accuracy]
metrics_dat = pd.concat(frames, axis = 1)
metrics_dat

sensitivity  specificity  balanced_accuracy
0     0.931373     0.591304           0.761338

In [221]:
### Need to get the predicted probabilities
pred_prob =  gs.predict_proba(X_test)
pred_prob[:,1]

array([0.99669075, 0.3039529 , 0.96171224, 0.9825471 , 0.1756365 ,
       0.96707445, 0.9858467 , 0.9787187 , 0.09378103, 0.9600673 ,
       0.6532217 , 0.8880726 , 0.9934697 , 0.87080246, 0.92724866,
       0.89548165, 0.15171881, 0.06846377, 0.8311499 , 0.9900345 ,
       0.04836588, 0.15171881, 0.98247564, 0.9875081 , 0.97913927,
       0.92019904, 0.05885879, 0.99715304, 0.9702219 , 0.9242021 ,
       0.88551176, 0.98533463, 0.9688826 , 0.79240763, 0.05203338,
       0.9898415 , 0.08801579, 0.75368285, 0.98339707, 0.59956837,
       0.971642  , 0.06794025, 0.94708323, 0.5736642 , 0.9567686 ,
       0.8592954 , 0.97044814, 0.5447576 , 0.27098116, 0.9658098 ,
       0.9899087 , 0.96157974, 0.55741775, 0.50520504, 0.96337575,
       0.9122038 , 0.49444118, 0.54873765, 0.04847186, 0.96531373,
       0.9711691 , 0.995182  , 0.04498342, 0.98862225, 0.87195045,
       0.9578738 , 0.8980047 , 0.997152  , 0.8923392 , 0.9879451 ,
       0.9693034 , 0.9891667 , 0.7545509 , 0.24176319, 0.99109

In [227]:
### Now save the model
import pickle
import joblib
filename = "gs.sav"
joblib.dump(gs, filename)
load_model = joblib.load(filename)
load_model

RandomizedSearchCV(cv=10, estimator=XGBClassifier(missing=nan), n_jobs=-1,
                   param_distributions={'alpha': [0, 0.1, 0.2, 0.3],
                                        'colsample_bytree': [0.5, 0.6, 0.7],
                                        'eta': [0.01, 0.001, 0.3],
                                        'lambda': [1, 1.1, 1.2, 1.3, 1.4],
                                        'max_depth': [6, 12, 15, 18],
                                        'scale_pos_weight ': [0.25, 0.5, 1],
                                        'subsample': [0.5, 0.6, 0.7]})